### ISSUE TITLE
Divide-by-zero Error

### ISSUE THREAD

**Issue by asposner** [B612-Asteroid-Institute/adam_home#139]
When running ADAM on main-belt asteroid Ivezic, since there are no impacts and no misses, the portion of the ADAM code that computes impact probability fails, due to a divide-by-zero error.

<img width="994" alt="Impact Prob Error" src="https://user-images.githubusercontent.com/14340/107707913-7c76ca80-6c77-11eb-97d6-20aa8e48c4d7.png">

**Comment by carise** [comment]
Update: there was an error in the input that caused the job to fail. We'll still need to do some better job progress and error reporting. I'll close this issue for now as the reporting features requests exist in the server code repository.
