### ISSUE TITLE
Add linter for automatic checks

### ISSUE THREAD

**Issue by samotiwala** [B612-Asteroid-Institute/adam_home#16]
Add linter (good option is flake8) to automated checks to ensure we have a consistent formatting standard

**Comment by laurahlark** [comment]
Remaining: lint stk client so we can remove it from flake8 exceptions.

**Comment by carise** [comment]
I'm going to close this and perhaps every quarter or twice a year, we should try to do a cleanup of code that has flake8 exceptions.
