### ISSUE TITLE
New encrypted test_config.json

### ISSUE THREAD

**Issue by EmmieKing** [B612-Asteroid-Institute/adam_home#68]
I have updated the unit tests in the Integration tests folder to use the new adam configuration. I named the file "test_adam_config.json" so the old file wouldn't get used. I believe this new file is created in Openssl and decoded from using the travis.yml and an encrypted file stored in the repo. Should this new file be generated with the same env/token of the previous version (test_config.json)? If so, I don't have this information. Who do you think is the best person to contact?

**Comment by EmmieKing** [comment]
Lowell and I are trying to test some Jupyter Notebooks that will need the new encrypted json file. I can generate it but I'll need to confirm the env/token information first. Does anyone have this information?

**Comment by laurahlark** [comment]
I have it. I’ll try to pull it up tonight.

**Comment by EmmieKing** [comment]
@laurahlark Did you have any luck finding the env/token information?

**Comment by AstrogatorJohn** [comment]
talked with @EmmieKing - wondering if we still need this in the repo

**Comment by carise** [comment]
As we are not using Travis for CI/CD, I will close this issue. Please let me know if that is a mistake.
