### ISSUE TITLE
Revise demo notebooks to use new 'standard' adam path.

### ISSUE THREAD

**Issue by EmmieKing** [B612-Asteroid-Institute/adam_home#69]
(1) delta_v_demo.ipynb:
insert cells 1 and 2, update cell 4 to use new config_file path
cell 9 -> AssertionError: 
Not equal to tolerance rtol=0, atol=0.001

(2) many_batch_run.ipynb:
insert cells 1 and 2, update cell 4 to use new config_file path
cell 7 -> Encountered error 503 calling get on /batch/d1bd1fb9-2e89-4672-b0fb-8e8e6d78d224/1?token=redacted: {'error': {'errors': [{'domain': 'global', 'reason': 'backendError', 'message': 'org.apache.shiro.session.ExpiredSessionException: Session with id [f3396f5e-b714-43d6-a9e1-9add8f62cd7e] has expired. Last access time: 12/3/18 7:02 PM.  Current time: 12/3/18 7:36 PM.  Session timeout is set to 1800 seconds (30 minutes)'}], 'code': 503, 'message': 'org.apache.shiro.session.ExpiredSessionException: Session with id [f3396f5e-b714-43d6-a9e1-9add8f62cd7e] has expired. Last access time: 12/3/18 7:02 PM.  Current time: 12/3/18 7:36 PM.  Session timeout is set to 1800 seconds (30 minutes)'}} 

(3) create_workspace.ipynb - I did not alter this notebook because of the note: "Can only be run by someone with sufficient access."

(4) permission_management_demo.ipynb - I did not alter this notebook because I don't think I have sufficient access to manage permissions.

(5) projects_demo.ipynb - insert cells 1 and 2, update cell 4, No Errors

(6) single_run_demo.ipynb - insert cells 1,2,3,5 and update cell 6, No Errors

**Comment by AstrogatorJohn** [comment]
Thanks, I'll try running them -

**Comment by carise** [comment]
I'm going to close this issue as we have a new configuration flow.
